export default {
  index: 'Overview',
  '-- atoms': {
    type: 'separator',
    title: 'Atoms',
  },
  avatar: 'Avatar',
  badge: 'Badge',
  button: 'Button',
  checkbox: 'Checkbox',
  input: 'Input',
  'progress-bar': 'ProgressBar',
  radio: 'Radio',
  skeleton: 'Skeleton',
  spinner: 'Spinner',
  switch: 'Switch',
  tag: 'Tag',
  tooltip: 'Tooltip',
  '-- molecules': {
    type: 'separator',
    title: 'Molecules',
  },
  alert: 'Alert',
  'amount-display': 'AmountDisplay',
  breadcrumb: 'Breadcrumb',
  'date-picker': 'DatePicker',
  dropdown: 'Dropdown',
  'empty-state': 'EmptyState',
  'form-field': 'FormField',
  'line-item': 'LineItem',
  pagination: 'Pagination',
  'price-display': 'PriceDisplay',
  'search-bar': 'SearchBar',
  stepper: 'Stepper',
  'status-badge': 'StatusBadge',
  tabs: 'Tabs',
  toast: 'Toast',
  '-- organisms': {
    type: 'separator',
    title: 'Organisms',
  },
  'data-table': 'DataTable',
  'filter-panel': 'FilterPanel',
  'metric-card': 'MetricCard',
  modal: 'Modal',
  'order-card': 'OrderCard',
  'order-summary': 'OrderSummary',
  'product-card': 'ProductCard',
  sidebar: 'Sidebar',
  'top-bar': 'TopBar',
};
